import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import React from "react";
import Navbar from "../components/header";
import Card from "@/components/card";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function Layout ({children}:{children:React.ReactNode}){
      // return <div><Navbar/>{children}</div>
      return <html lang="en">
      <body className={inter.className}>
        <Navbar/>
        <Card/>
        {children}
       
      </body>
    </html>
}
export default Layout;